#!/bin/sh

BUILD_DATE=$( date +%Y-%m-%d\ %H:%M )
BRANCH=$( git rev-parse --abbrev-ref HEAD )
REVISION=$( git rev-parse --short HEAD )
KUBE_VERSION="0.9.1"

echo "// autogenerated. Don't edit!"
echo
echo "package version"
echo
echo "const ("
echo "  BUILD_DATE = \"${BUILD_DATE}\""
echo "  BRANCH = \"${BRANCH}\""
echo "  REVISION = \"${REVISION}\""
echo "  KUBEVERSION = \"${KUBE_VERSION}\""
echo ")"

