---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-metrics-collector
  namespace: kubevirt
  labels:
    kubevirt.io: ""
---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-hostpath
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:kubevirt:kubevirt-metrics-collector
volumes:
- hostPath

